---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chukmunnlee/soda-demos.git
    path: application/manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: api-ns
  syncPolicy:
    automated: {}
      #prune: true
      #selfHeal: true
    syncOptions:
    - CreateNamespace=true
