---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chukmunnlee/soda-demos.git
    path: application/manifests
    targetRevision: HEAD
    kustomize:
      images:
      - name: api-container
        newTag: v1

  destination:
    server: https://kubernetes.default.svc
    namespace: api-ns
  syncPolicy:
    automated: null
      #prune: true
      #selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: argoproj.io
    kind: Rollout
    name: api-ro
    jsonPointers:
    - /spec/replicas
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: api-httproute
    namespace: api-ns
    jsonPointers:
    - /spec/rules/0/backendRefs/0/weight
    - /spec/rules/0/backendRefs/1/weight

