---
apiVersion: v1
kind: Namespace
metadata:
  name: dov-ns

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: dov-ns
spec:
  type: ClusterIP
  selector:
    app: dov
    name: dov-po
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: dov-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dov
      name: dov-po
  template:
    metadata:
      labels:
        app: dov
        name: dov-po
    spec:
      containers:
      - name: dov-container
        image: chukmunnlee/dov-bear:v5
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          value: dov-bear
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dov-httproute
  namespace: dov-ns
spec:
  hostnames:
  - dov.192.168.39.200.sslip.io
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    sectionName: web
  rules:
  - matches:
    - path:
        value: /
        type: PathPrefix
    backendRefs:
    - name: dov-svc
      port: 3000
